services:
  api_roveni:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - uploads_roveni_data:/app/uploads
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db_roveni:5432/${DB_NAME}?sslmode=disable
      - REDIS_URL=redis://cache_roveni:6379/0
      - PORT=${PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - db_roveni
      - cache_roveni
    networks:
      - default

  db_roveni:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_roveni_data:/var/lib/postgresql/data
    networks:
      - default

  cache_roveni:
    image: redis:7-alpine
    volumes:
      - redis_roveni_data:/data
    networks:
      - default

volumes:
  postgres_roveni_data:
  redis_roveni_data:
  uploads_roveni_data:

networks:
  default: